export enum AppStoreEnum {
  ROUTESLIST = "ROUTESLIST",
  SETPAGELOADING = "SETPAGELOADING",
  SETPROJECTCONFIG = "SETPROJECTCONFIG",
}

export const ROUTESLIST = "ROUTESLIST";

export const SETPAGELOADING = "SETPAGELOADING";

// 项目配置
export const SETPROJECTCONFIG = 'SETPROJECTCONFIG';